# Investor 01
[[redirects]]
  from = "/dataroom/gate"
  to = "https://drive.google.com/drive/folders/1brnHQJh4WDuKUAuZB8LTsYFhdi05kNhl?usp=drive_link"
  status = 302
  force = true

# Investor 02
[[redirects]]
  from = "/dataroom/helmet"
  to = "https://drive.google.com/drive/folders/1rJu7D1IMjHevtm2GLg4nFFOCPPr3B4qn?usp=sharing"
  status = 302
  force = true

# Investor 03
[[redirects]]
  from = "/dataroom/shovel"
  to = "https://drive.google.com/drive/folders/1HL7xFl1L6fCIHqfKE6jVYxrkJacflMVY?usp=sharing"
  status = 302
  force = true

# Investor 04
[[redirects]]
  from = "/dataroom/permit"
  to = "https://drive.google.com/drive/folders/1t9561oAxuS9RFSzxJa4AoAnRrIgI0ttI?usp=drive_link"
  status = 302
  force = true 
